SHOW DATABASES;
USE day_4_9_db;


SHOW TABLES;

SELECT * FROM customers;

-- 主キーでUPDATE(行ロック)
UPDATE customers SET age=43 WHERE id=1;
ROLLBACK;

-- 主キーの指定なしでテーブル全体のロックがされます
START TRANSACTION;
UPDATE customers SET age=42 WHERE name="河野 文典";
ROLLBACK;

-- DELETE 
START TRANSACTION;
DELETE FROM customers WHERE id=1;
COMMIT;

-- INSERT
ALTER TABLE customers DROP COLUMN name_length;
START TRANSACTION;
INSERT INTO customers VALUES(1,"田中 一郎", 21, "1991-01-10");
SELECT * FROM customers;
ROLLBACK;


-- SELECTのロック
-- FOR SHARE(共有ロック)
-- FOR UPDATE(排他ロック)
START TRANSACTION;
SELECT * FROM customers WHERE id=1 FOR SHARE;
ROLLBACK ;


START TRANSACTION;
SELECT * FROM customers WHERE id=1 FOR UPDATE;
ROLLBACK ;

-- LOCK TABLE READ
LOCK TABLE customers READ;
SELECT * FROM customers;
UPDATE customers SET age=42 WHERE id=1;

UNLOCK TABLES;

-- LOCK TABLE WRITE
 LOCK TABLE customers WRITE;
SELECT * FROM customers;
UPDATE customers SET age=42 WHERE id=1;

UNLOCK TABLES;


-- DEAD LOCK 
START TRANSACTION;
-- customers ⇨ users
UPDATE customers SET age=42 WHERE id=1;
UPDATE users SET age=12 WHERE id=1;

